config/routes.rb
KIT2PlusB::Application.routes.draw do
  root :to => 'pages#welcome'

  match '/welcome'   => 'pages#welcome',   :as => "welcome",   :via => :get
  match '/goodbye'   => 'pages#goodbye',   :as => "goodbye",   :via => :get
  match '/dashboard' => 'pages#dashboard', :as => "dashboard", :via => :get
  match '/downloads' => 'pages#downloads', :as => "downloads", :via => :get

  resources :participants,  :except => [:edit, :update]
  resources :demographics,  :except => [:edit, :update]
  resources :graphics,      :except => [:edit]
  resources :searches,      :except => [:edit] do
    collection do
      get 'nested_download'
    end
  end
  resources :source_evaluations, :only => [:index]
  resources :questionnaires,:except => [:edit]

end

app/models/participant.rb
# == Schema Information
# Schema version: 20120427031241
#
# Table name: participants
#
#  id               :integer         not null, primary key
#  session_id       :string(255)
#  ip_address       :string(255)
#  first_name       :string(255)
#  last_name        :string(255)
#  instructor       :string(255)
#  country          :string(255)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  current_question :integer         default(0)
#

class Participant < ActiveRecord::Base
  attr_accessible :country, :first_name, :instructor, :last_name
  
  validates_presence_of :session_id
  validates_presence_of :ip_address
  
  validates_presence_of :country
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :instructor
  
  has_one :demographic, :class_name => "Demographic", :foreign_key => "participant_id", :dependent => :destroy
  has_one :graphic, :class_name => "Graphic", :foreign_key => "participant_id", :dependent => :destroy
  has_one :search, :class_name => "Search", :foreign_key => "participant_id", :dependent => :destroy
  has_one :questionnaire, :class_name => "Questionnaire", :foreign_key => "participant_id", :dependent => :destroy
  
  def ad_test
    return nil if search.nil?
    return search.ad_test
  end
  
  def progress
    demographic_steps = 1
    graphic_steps = 8
    search_steps = 6
    questionnaire_steps = 14
    
    total_steps = demographic_steps + graphic_steps + search_steps + questionnaire_steps
    steps_finished = 0
    steps_finished += demographic_steps unless demographic.nil?
    steps_finished += graphic.step unless graphic.nil?
    steps_finished += search.step unless search.nil?
    steps_finished += questionnaire.step unless questionnaire.nil?
    
    return ((steps_finished.to_f / total_steps) * 100).to_i
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_filter :authenticate_admin, :only => [:index, :show, :destroy]

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @participants }
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << ["id","ip_address", "first_name", "last_name", "instructor", "country", "created_at", "updated_at"]
          @participants.each do |p|
            csv << [p.id, p.ip_address, p.first_name, p.last_name, p.instructor, p.country, p.created_at, p.updated_at]
          end
        end

        send_data csv_string, :type => 'text/csv; charset=iso-8859-1; header=present',
                              :disposition => "attachment; filename=participants.csv"
      }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    p = Participant.find_by_session_id(session[:session_id])
    unless p.nil?
      redirect_to new_demographic_path
      return
    end
    
    @participant = Participant.new
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])
    @participant.session_id = session[:session_id]
    @participant.ip_address = request.ip

    respond_to do |format|
      if @participant.save
        format.html { redirect_to new_demographic_path }
      else
        format.html { render action: "new" }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :no_content }
    end
  end
  
  private
  
  def authenticate_admin
    authenticate_or_request_with_http_basic do |user, password|
      user == ENV["ADMIN_USER"] && password == ENV["ADMIN_PASS"]
    end
  end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for @participant, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :object => f.object %>
  
  <div class="row">
    <div class="span5">
      <div class="control-group">
        <%= f.label :first_name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :first_name, :class => 'text_field', :placeholder => "i.e., Jane" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :last_name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :last_name, :class => 'text_field', :placeholder => "i.e., Smith" %>
        </div>
      </div>
    </div>
    <div class="span5">
      <div class="control-group">
        <%= f.label :instructor, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :instructor, :class => 'text_field', :placeholder => "i.e., Dr. Alexander" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :country, :class => 'control-label' %>
        <div class="controls">
          <%= f.select :country, options_for_select(["USA", "Israel", "Netherlands", "New Zealand"]) %>
        </div>
      </div>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit "I consent", :class => 'btn btn-primary' %>
    <%= link_to "I decline", goodbye_path(:decline => true), :class => 'btn' %>
  </div>
<% end %>

app/views/participants/index.html.erb
<%- model_class = Participant.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:session_id) %></th>
      <th><%= model_class.human_attribute_name(:ip_address) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:instructor) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= link_to participant.id, participant_path(participant) %></td>
        <td><%= participant.session_id %></td>
        <td><%= participant.ip_address %></td>
        <td><%= participant.first_name %></td>
        <td><%= participant.last_name %></td>
        <td><%= participant.instructor %></td>
        <td><%= participant.country %></td>
        <td><%=l participant.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      participant_path(participant),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_participant_path,
            :class => 'btn btn-primary' %>

app/views/participants/new.html.erb
<h1>Consent Form # 09-0329</h1>
<br>
<table class="table table-bordered table-striped">
  <tbody>
    <tr>
      <td>Project Title</td>
      <td>Knowledge, Information, and Truth in an Online World</td>
    </tr>
    <tr>
      <td>Why is this research being done?</td>
      <td>
        <p>
          This is a research project being conducted by researchers at the University of Maryland, College Park, USA. 
          We are inviting you to participate in this research project because you are an undergraduate or graduate student in university.
        </p>
        <p>
          Technological advances have brought about vast changes in the worlds of information and communication in recent years. Students growing up immersed in a high-speed, trend-conscious, constantly-connected culture may have experienced a consequent shift in their understandings of the interrelated constructs of knowledge, information, and truth. The purpose of this research project is to investigate this possible shift, by taking the initial step of inquiring about students' understandings of these constructs.
        </p>
      </td>
    </tr>
    <tr>
      <td>What will I be asked to do?</td>
      <td>
        <p>
          The procedures involve completing a series of three measures in a computer-based environment that supports a simulated online (i.e., world wide web) search task. These measures will be completed outside the classroom or regular class time. Participation will require access to a computer with an Internet connection. If you do not have access to your own personal computer, you will be directed to computer labs on campus. You will be directed how to access the website supporting this environment in a handout provided by your instructor; in addition, you will be encouraged to contact the researchers if you need assistance.
        </p>
        <p>
          All data collected will be stored on an external server. Data will be sent from the student's personal computer to a secure external server. First, you will complete the consent form and a demographic information sheet. Next, you will select from graphic representations of the interrelations between knowledge, information, and truth, define these terms, and provide an explanation. You will be asked about your background knowledge and interest. You will then perform a search task that addresses first a factual and then a more interpretive question regarding astrophysics and developmental psychology, using a set of 7 possible sources. During this task, data will be collected including: source accessed, duration of access, and source evaluation. Finally, you will complete a questionnaire about your beliefs and attitudes towards inquiry; this involves completing the same set of 41 items twice, for two different contexts. Completion of all measures is expected to take approximately 45 minutes.
        </p>
      </td>
    </tr>
    <tr>
      <td>What about confidentiality?</td>
      <td>
        <p>
          We will do our best to keep your personal information confidential. To help protect your confidentiality, (1) your name will not be included on the surveys and other collected data; (2) a code will be placed on the survey and other collected data; (3) through the use of an identification key, the researcher will be able to link your survey to your identity; and (4) only the researcher will have access to the identification key. For open-ended responses, only brief quotations will be used, if at all, and care will be taken not to reveal your identity through the use of quotes. These steps ensure that participants' personal information will not be associated with the collected data.
        </p>
        <p>
          All data, including a USB drive containing completed measures and logfiles, will remain in a locked filing cabinet for a period of five years. This cabinet is located in the Disciplined Reading and Learning Research Lab (Room 3240 Benjamin Building, Department of Human Development, University of Maryland, College Park, MD 20742, USA). After this time, the data will be either destroyed or boxed and moved to another secure storage facility. If destruction is deemed appropriate, the paper documents will be shredded and placed in a storage container, and the USB drive will be erased.
        </p>
        <p>
          Access to these data will be limited to: the student investigators (doctoral students in the Disciplined Reading and Learning Research Lab), and the primary investigator (a tenured full professor in the Department of Human Development). These graduate students are instructed as to the ethical nature of data collections and the importance of maintaining the confidentiality of study participants.
        </p>
        <p>
          If we write a report or article about this research project, your identity will be protected to the maximum extent possible. Your information may be shared with representatives of the University of Maryland, College Park or governmental authorities if you or someone else is in danger or if we are required to do so by US law.
        </p>
        <p>
          In accordance with legal requirements and/or professional standards, we will disclose to the appropriate individuals and/or authorities information that comes to our attention concerning child abuse or neglect or potential harm to you or others.
        </p>
      </td>
    </tr>
    <tr>
      <td>What are the risks of this research?</td>
      <td>
        <p>
          There may be some risks from participating in this research study. Specifically, completion of the measures requires cognitive effort for a sustained period of time and may generate frustration in some students.
        </p>
      </td>
    </tr>
    <tr>
      <td>What are the benefits of this research?</td>
      <td>
        <p>
          This research is not designed to help you personally, but the results may help the investigator learn more about how context and type of experience are related to epistemic orientations. We hope that, in the future, other people might benefit from this study through improved understanding of students' perception of the relation between knowledge, interest, and strategies.
        </p>
      </td>
    </tr>
    <tr>
      <td>Do I have to be in this research? May I stop participating at any time?</td>
      <td>
        <p>
          Your participation in this research is completely voluntary. You may choose not to take part at all. If you decide to participate in this research, you may stop participating at any time. If you decide not to participate in this study or if you stop participating at any time, you will not be penalized or lose any benefits to which you otherwise qualify.
        </p>
      </td>
    </tr>
    
    <tr>
      <td>What if I have questions?</td>
      <td>
        <p>
          This research is being conducted by Dr. Patricia Alexander and the Human Development department at the University of Maryland, College Park. If you have any questions about the research study itself, please contact Dr. Alexander at: Disciplined Reading and Learning Research Lab, Room 3240 Benjamin Building, Department of Human Development, University of Maryland, College Park, MD 20742, USA), by telephone at (301) 405-6956, or by email at <%= link_to "palexand@umd.edu", "mailto:palexand@umd.edu?subject=[DRLRL Study] IRB Inquiry" %>. If you have questions about your rights as a research subject or wish to report a research-related injury, please contact: Institutional Review Board Office, University of Maryland, College Park, Maryland, 20742, USA; (e-mail) <%= link_to "irb@deans.umd.edu", "mailto:irb@deans.umd.edu?subject=[DRLRL Study] IRB Inquiry" %>; (telephone) 301-405-0678
        </p>
        <p>
          This research has been reviewed according to the University of Maryland, College Park IRB procedures for research involving human subjects.
        </p>
      </td>
    </tr>
    <tr>
      <td>Statement of Age of Subject and Consent</td>
      <td>
        <p>
          Please enter your name below to provide your consent. Your consent indicates that:
          you are at least 18 years of age;
          the research has been explained to you;
          your questions have been fully answered; and
          you freely and voluntarily choose to participate in this research
          project.
        </p>
      </td>
    </tr>    
  </tbody>
</table>

<%= render 'form' %>

app/views/participants/show.html.erb
<%- model_class = @participant.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:session_id) %>:</strong><br>
  <%= @participant.session_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:ip_address) %>:</strong><br>
  <%= @participant.ip_address %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:first_name) %>:</strong><br>
  <%= @participant.first_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:last_name) %>:</strong><br>
  <%= @participant.last_name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:instructor) %>:</strong><br>
  <%= @participant.instructor %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:country) %>:</strong><br>
  <%= @participant.country %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              participants_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              participant_path(@participant),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>