config/routes.rb
KIT2PlusB::Application.routes.draw do
  root :to => 'pages#welcome'

  match '/welcome'   => 'pages#welcome',   :as => "welcome",   :via => :get
  match '/goodbye'   => 'pages#goodbye',   :as => "goodbye",   :via => :get
  match '/dashboard' => 'pages#dashboard', :as => "dashboard", :via => :get
  match '/downloads' => 'pages#downloads', :as => "downloads", :via => :get

  resources :participants,  :except => [:edit, :update]
  resources :demographics,  :except => [:edit, :update]
  resources :graphics,      :except => [:edit]
  resources :searches,      :except => [:edit] do
    collection do
      get 'nested_download'
    end
  end
  resources :source_evaluations, :only => [:index]
  resources :questionnaires,:except => [:edit]

end

app/models/graphic.rb
# == Schema Information
# Schema version: 20120427193221
#
# Table name: graphics
#
#  id               :integer         not null, primary key
#  participant_id   :integer
#  graphics_ki      :integer
#  graphics_ki_text :text
#  graphics_kt      :integer
#  graphics_kt_text :text
#  graphics_it      :integer
#  graphics_it_text :text
#  k_def            :text
#  i_def            :text
#  t_def            :text
#  kit              :text
#  context          :text
#  domain           :text
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  step             :integer         default(0)
#

class Graphic < ActiveRecord::Base
  attr_accessible :context, :domain, :graphics_it_text, :graphics_it, :graphics_ki, :graphics_ki_text 
  attr_accessible :graphics_kt, :graphics_kt_text, :i_def, :k_def, :kit, :participant_id, :t_def
  
  belongs_to :participant, :class_name => "Participant", :foreign_key => "participant_id"
  
  # validates_presence_of :participant_id
  validates_presence_of :graphics_ki
  validates_presence_of :graphics_ki_text, :if => Proc.new{ |f| f.step > 1 }
  validates_presence_of :graphics_kt, :if => Proc.new{ |f| f.step > 2 }
  validates_presence_of :graphics_kt_text, :if => Proc.new{ |f| f.step > 3 }
  validates_presence_of :graphics_it, :if => Proc.new{ |f| f.step > 4 }
  validates_presence_of :graphics_it_text, :if => Proc.new{ |f| f.step > 5 }
  validates_presence_of :k_def, :if => Proc.new{ |f| f.step > 6 }
  validates_presence_of :i_def, :if => Proc.new{ |f| f.step > 6 }
  validates_presence_of :t_def, :if => Proc.new{ |f| f.step > 6 }
  validates_presence_of :kit, :if => Proc.new{ |f| f.step > 6 }
  validates_presence_of :context, :if => Proc.new{ |f| f.step > 7 }
  validates_presence_of :domain, :if => Proc.new{ |f| f.step > 7 }
end

app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController
  before_filter :authenticate_admin, :only => [:index, :show, :destroy]
  before_filter :go_to_consent, :only => [:new, :create, :update]
  
  # GET /graphics
  # GET /graphics.json
  def index
    @graphics = Graphic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @graphics }
      format.csv {
        csv_string = CSV.generate do |csv|
          csv << ["id", "participant_id", "graphics_ki", "graphics_ki_text", "graphics_kt", "graphics_kt_text",
                  "graphics_it", "graphics_it_text", "k_def", "i_def", "t_def", "kit", "context", "domain", 
                  "created_at", "updated_at"]
          @graphics.each do |g|
            csv << [g.id, g.participant_id, g.graphics_ki, g.graphics_ki_text, g.graphics_kt, g.graphics_kt_text, 
                    g.graphics_it, g.graphics_it_text, g.k_def, g.i_def, g.t_def, g.kit, g.context, g.domain, 
                    g.created_at, g.updated_at]
          end
        end

        send_data csv_string, :type => 'text/csv; charset=iso-8859-1; header=present',
                              :disposition => "attachment; filename=graphics.csv"
      }
    end
  end

  # GET /graphics/1
  # GET /graphics/1.json
  def show
    @graphic = Graphic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @graphic }
    end
  end

  # GET /graphics/new
  # GET /graphics/new.json
  def new    
    @graphic = current_graphic || Graphic.new

    if @graphic.step > 7
      redirect_to new_search_path
      return
    end

    respond_to do |format|
      format.html { render "graphics/steps/step#{@graphic.step}" }
      format.json { render json: @graphic }
    end
  end

  # POST /graphics
  # POST /graphics.json
  def create
    @graphic = current_participant.build_graphic(params[:graphic])
    @graphic.step = 1

    respond_to do |format|
      if @graphic.save
        format.html { redirect_to new_graphic_path }
        # format.json { render json: @graphic, status: :created, location: @graphic }
      else
        format.html { render "graphics/steps/step0" }
        # format.json { render json: @graphic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /graphics/1
  # PUT /graphics/1.json
  def update
    @graphic = current_graphic
    @graphic.step += 1

    respond_to do |format|
      if @graphic.update_attributes(params[:graphic])
        format.html { redirect_to new_graphic_path }
        # format.json { head :no_content }
      else
        format.html { render "graphics/steps/step#{@graphic.step - 1}" }
        # format.json { render json: @graphic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graphics/1
  # DELETE /graphics/1.json
  def destroy
    @graphic = Graphic.find(params[:id])
    @graphic.destroy

    respond_to do |format|
      format.html { redirect_to graphics_url }
      format.json { head :no_content }
    end
  end
  
  private 
  
  def current_participant
    @participant = Participant.find_by_session_id(session[:session_id])
  end
  
  def current_graphic
    if @participant.nil?
      return nil
    else
      return @participant.graphic
    end
  end
    
  def authenticate_admin
    authenticate_or_request_with_http_basic do |user, password|
      user == ENV["ADMIN_USER"] && password == ENV["ADMIN_PASS"]
    end
  end
  
  def go_to_consent
    current_participant
    if @participant.nil?
      flash[:alert] = "Sorry we need you to consent first."
      redirect_to new_participant_path
    end
    
    if @participant.demographic.nil?
      flash[:alert] = "Sorry we need your demographic info first."
      redirect_to new_demographic_path
    end
  end
end

app/helpers/graphics_helper.rb
module GraphicsHelper
end

app/views/graphics/_form.html.erb
<%= form_for @graphic, :html => { :class => 'form-horizontal' } do |f| %>
  <%= render "shared/error_messages", :object => f.object %>

  <div class="control-group">
    <%= f.label :graphics_ki, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :graphics_ki, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :graphics_ki_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :graphics_ki_text, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :graphics_kt, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :graphics_kt, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :graphics_it, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :graphics_it, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :graphics_it_text, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :graphics_it_text, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :k_def, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :k_def, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :i_def, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :i_def, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :t_def, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :t_def, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :kit, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :kit, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :context, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :context, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :domain, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :domain, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Next Question", :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/graphics/edit.html.erb
<%- model_class = @graphic.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/graphics/index.html.erb
<%- model_class = Graphic.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:participant_id) %></th>
      <th><%= model_class.human_attribute_name(:graphics_ki) %></th>
      <th><%= model_class.human_attribute_name(:graphics_ki_text) %></th>
      <th><%= model_class.human_attribute_name(:graphics_kt) %></th>
      <th><%= model_class.human_attribute_name(:graphics_it) %></th>
      <th><%= model_class.human_attribute_name(:graphics_it_text) %></th>
      <th><%= model_class.human_attribute_name(:k_def) %></th>
      <th><%= model_class.human_attribute_name(:i_def) %></th>
      <th><%= model_class.human_attribute_name(:t_def) %></th>
      <th><%= model_class.human_attribute_name(:kit) %></th>
      <th><%= model_class.human_attribute_name(:context) %></th>
      <th><%= model_class.human_attribute_name(:domain) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @graphics.each do |graphic| %>
      <tr>
        <td><%= link_to graphic.id, graphic_path(graphic) %></td>
        <td><%= graphic.participant_id %></td>
        <td><%= graphic.graphics_ki %></td>
        <td><%= graphic.graphics_ki_text %></td>
        <td><%= graphic.graphics_kt %></td>
        <td><%= graphic.graphics_it %></td>
        <td><%= graphic.graphics_it_text %></td>
        <td><%= graphic.k_def %></td>
        <td><%= graphic.i_def %></td>
        <td><%= graphic.t_def %></td>
        <td><%= graphic.kit %></td>
        <td><%= graphic.context %></td>
        <td><%= graphic.domain %></td>
        <td><%=l graphic.created_at %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      graphic_path(graphic),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_graphic_path,
            :class => 'btn btn-primary' %>

app/views/graphics/new.html.erb
<h1>Graphics Task</h1>
<br>
<%= render :partial => 'form' %>

app/views/graphics/show.html.erb
<%- model_class = @graphic.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:participant_id) %>:</strong><br>
  <%= @graphic.participant_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:graphics_ki) %>:</strong><br>
  <%= @graphic.graphics_ki %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:graphics_ki_text) %>:</strong><br>
  <%= @graphic.graphics_ki_text %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:graphics_kt) %>:</strong><br>
  <%= @graphic.graphics_kt %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:graphics_it) %>:</strong><br>
  <%= @graphic.graphics_it %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:graphics_it_text) %>:</strong><br>
  <%= @graphic.graphics_it_text %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:k_def) %>:</strong><br>
  <%= @graphic.k_def %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:i_def) %>:</strong><br>
  <%= @graphic.i_def %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:t_def) %>:</strong><br>
  <%= @graphic.t_def %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:kit) %>:</strong><br>
  <%= @graphic.kit %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:context) %>:</strong><br>
  <%= @graphic.context %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:domain) %>:</strong><br>
  <%= @graphic.domain %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              graphics_path, :class => 'btn'  %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              graphic_path(@graphic),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>